# -*- coding: utf-8 -*-
# *** Config version 0.1.0 ***
### Important values are marked with
### This file MUST be in UTF-8 encoding
### Restart the Apps/APIs after modifying
### Alway use forward slash /
### '%' char must be doubled:  %%

[pdf-wtf]
